// Requires the `reasoning` module generated by build.rs (Step 3).
use cubelang::reasoning::{RunRequest, RunResult, run_result};
use prost::Message;

#[test]
fn run_request_and_result_roundtrip_through_prost() {
    let req = RunRequest { program: "program P {}".into(), args: vec!["x".into()], fn_name: "solve".into() };
    let mut buf = Vec::new();
    req.encode(&mut buf).unwrap();
    let back = RunRequest::decode(&buf[..]).unwrap();
    assert_eq!(back.fn_name, "solve");
    assert_eq!(back.args, vec!["x".to_string()]);

    let res = RunResult { ok: true, result: Some(run_result::Result::Symbol("cat".into())), similarity: None };
    let mut b2 = Vec::new();
    res.encode(&mut b2).unwrap();
    match RunResult::decode(&b2[..]).unwrap().result {
        Some(run_result::Result::Symbol(s)) => assert_eq!(s, "cat"),
        other => panic!("expected Symbol(cat), got {:?}", other),
    }
}
