// Requires the `run-proto` subcommand (Task 4) and the `reasoning` module
// generated by build.rs (Task 3). Drives the real compiled `cubelang`
// binary as a subprocess over stdin/stdout -- the exact transport Task 5's
// Python client will use -- rather than calling anything in-process, so this
// proves the actual wire behavior end to end, not just the mapping function.
use cubelang::reasoning::{RunRequest, RunResult, run_result};
use prost::Message;
use std::io::{Read, Write};
use std::process::{Command, Stdio};

fn call_proto(req: RunRequest) -> RunResult {
    let exe = env!("CARGO_BIN_EXE_cubelang");
    let mut child = Command::new(exe).arg("run-proto")
        .stdin(Stdio::piped()).stdout(Stdio::piped()).spawn().unwrap();
    let mut buf = Vec::new(); req.encode(&mut buf).unwrap();
    let mut stdin = child.stdin.take().unwrap();
    stdin.write_all(&(buf.len() as u32).to_be_bytes()).unwrap();
    stdin.write_all(&buf).unwrap();
    drop(stdin);
    let mut out = Vec::new();
    child.stdout.take().unwrap().read_to_end(&mut out).unwrap();
    child.wait().unwrap();
    let len = u32::from_be_bytes(out[..4].try_into().unwrap()) as usize;
    RunResult::decode(&out[4..4 + len]).unwrap()
}

#[test]
fn proto_stdio_runs_a_recover_program() {
    let program = r#"
use vsa;
program R implements ISolve {
    public function solve(input: str): str {
        create frame: number;
        bind frame, SUBJECT, "cat";
        bind frame, OBJECT, "mouse";
        return recover(frame, SUBJECT);
    }
}
"#;
    let res = call_proto(RunRequest { program: program.into(), args: vec!["_".into()], fn_name: "solve".into() });
    assert!(res.ok);
    assert!(matches!(res.result, Some(run_result::Result::Symbol(ref s)) if s == "cat"));
    // Task 7 (Feature A, similarity-surfacing): a clean single-pair
    // bind->unbind recovery must surface a high-confidence similarity
    // alongside the symbol, not just the symbol. Empirically ~0.52 here
    // (deterministic: fixed codebook seed + fixed symbol names) -- a
    // 2-pair MAP-Bipolar bundle's recovered-role cosine sim centers near
    // 0.5 by construction (half the dims recover exactly, the other half
    // are a coin flip from cross-talk), so 0.3 is the threshold that
    // actually separates "real recovery" from noise: it's ~3x the <0.1
    // near-orthogonal ceiling this repo's own hypervec.rs tests use, with
    // real headroom below the observed value on the other side.
    assert!(res.similarity.is_some(), "solve's clean recover() must surface Some(similarity)");
    assert!(res.similarity.unwrap() > 0.3,
        "clean bind->unbind recovery should score well above chance/noise, got {:?}", res.similarity);
}

// ── wrong_role / unbound over the wire ──────────────────────────────────────
//
// The test above only exercises the right-role case. Task 5 will assert all
// three M1 control cases (solve -> cat, wrong_role -> mouse, unbound ->
// None) over protobuf, matching `cubbyllm/bridges/programs/reasoning_bridge
// .cube` (CubbyLLM repo) and its `test_reasoning_bridge.py`. Proven here so
// the value-mapping -- especially unbound's oneof-UNSET requirement -- is
// caught now, not discovered broken in Task 5.

/// Mirrors `cubbyllm/bridges/programs/reasoning_bridge.cube` exactly: one
/// frame binds SUBJECT->"cat" and OBJECT->"mouse", and three functions
/// exercise the three M1 control cases (right role, wrong role, never-bound
/// role).
fn reasoning_bridge_program() -> &'static str {
    r#"
use vsa;
program ReasoningBridge implements ISolve {
    public function solve(mention: str): str {
        create frame: number;
        bind frame, SUBJECT, "cat";
        bind frame, OBJECT, "mouse";
        return recover(frame, SUBJECT);
    }

    # control: a different role in the same frame recovers a different filler
    public function wrong_role(): str {
        create frame: number;
        bind frame, SUBJECT, "cat";
        bind frame, OBJECT, "mouse";
        return recover(frame, OBJECT);
    }

    # control: an unbound frame recovers no symbol
    public function unbound(): str {
        create frame: number;
        return recover(frame, SUBJECT);
    }
}
"#
}

#[test]
fn proto_stdio_wrong_role_recovers_mouse_not_cat() {
    let res = call_proto(RunRequest {
        program: reasoning_bridge_program().into(),
        args: vec![],
        fn_name: "wrong_role".into(),
    });
    assert!(res.ok, "wrong_role must succeed (ok:true)");
    match res.result {
        Some(run_result::Result::Symbol(ref s)) => assert_eq!(s, "mouse", "wrong-role control must recover a different filler than SUBJECT's"),
        other => panic!("expected Symbol(\"mouse\"), got {:?}", other),
    }
    // Task 7: same as `solve` -- a real, clean recovery (just of the other
    // role in the same frame) must also carry a similarity well clear of
    // noise. Empirically ~0.486 here; see `solve`'s test above for why 0.3,
    // not 0.5, is the right cutoff for a 2-pair bundle recovery.
    assert!(res.similarity.is_some(), "wrong_role's clean recover() must surface Some(similarity)");
    assert!(res.similarity.unwrap() > 0.3,
        "clean bind->unbind recovery should score well above chance/noise, got {:?}", res.similarity);
}

#[test]
fn proto_stdio_unbound_maps_to_unset_oneof_not_symbol_null() {
    let res = call_proto(RunRequest {
        program: reasoning_bridge_program().into(),
        args: vec![],
        fn_name: "unbound".into(),
    });
    // recover() legitimately finding no bound filler is a successful run,
    // not an error -- matches M1's JSON path, which reports ok:true with
    // result:null for this same program/fn.
    assert!(res.ok, "unbound must still be ok:true; finding no filler isn't a runtime error");
    // The whole point of this test: the unbound/absent-role case must leave
    // the oneof UNSET (so the Python side decodes `None`, matching M1's JSON
    // `null`) -- NOT a stringified `Symbol("null")`, which would silently
    // break the absent-role control on the Python side (Task 5).
    match res.result {
        None => {}
        Some(other) => panic!(
            "unbound recover() must map to an UNSET oneof (Python None), got {:?}", other
        ),
    }
    // Task 7: no winning match means no similarity either -- `similarity`
    // must be unset (None) exactly when `symbol` is, not e.g. Some(0.0).
    assert!(res.similarity.is_none(),
        "unbound recover() must leave similarity unset too (no winning match), got {:?}", res.similarity);
}
